language: r
sudo: required

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "install.packages('XML', repos = 'http://cran.rstudio.com/')" && R CMD javareconf && R -e "install.packages('rJava', type='source')"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y && sudo apt-get install r-cran-xml libgsl0-dev -y ; fi
  
warnings_are_errors: false
