language: r
sudo: false
cache: packages

os:
  - linux
  - osx


addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels
      - r-cran-xml
      
     
      
warnings_are_errors: false


